const API='https://api.guerrillamail.com/ajax.php';
const S={accounts:[],active:null,messages:[],timer:null,history:[],vault:false,key:null};
const $=id=>document.getElementById(id); const esc=s=>(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(m){$('toast').textContent=m;$('toast').classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>$('toast').classList.remove('show'),2800)}
function friendly(e){const s=String(e?.message||e);if(/429|busy/i.test(s))return 'The relay is busy. Give it a minute, then try again.';if(/Failed to fetch|network/i.test(s))return 'The relay cannot be reached right now. Your browser and local history are still safe.';return 'The relay paused unexpectedly. Nothing private was exposed. Try again in a moment.'}
async function relay(f,params={},token){const q=new URLSearchParams({f,lang:'en',...params});if(token)q.set('sid_token',token);const r=await fetch(`${API}?${q}`);if(!r.ok)throw new Error(`relay ${r.status}`);return r.json()}
async function init(){loadSession();bind();setApi(null);try{await relay('get_email_address');setApi(true)}catch(e){setApi(false)}render();if(S.active)selectAccount(S.active)}
function setApi(ok){$('apiState').textContent=ok===true?'Relay online':ok===false?'Relay unavailable':'Checking relay';$('apiDot').parentElement.classList.toggle('ok',ok===true)}
function bind(){['newBtn','heroCreate'].forEach(id=>$(id).onclick=()=>{$('createPanel').hidden=false;$('aliasInput').focus()});$('cancelCreate').onclick=()=>{$('createPanel').hidden=true};$('createBtn').onclick=createAccount;$('aliasInput').onkeydown=e=>{if(e.key==='Enter')createAccount()};$('copyBtn').onclick=()=>copy(S.active?.address);$('refreshBtn').onclick=()=>poll(true);$('deleteBtn').onclick=burn;$('intervalSelect').onchange=startPolling;$('historyBtn').onclick=()=>{$('historyPanel').hidden=!$('historyPanel').hidden};$('qrBtn').onclick=showQR;$('privacyBtn').onclick=()=>openModal('privacyModal');$('vaultBtn').onclick=()=>openModal('vaultModal');document.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>x.closest('.modal-wrap').hidden=true);document.querySelectorAll('.modal-wrap').forEach(x=>x.onclick=e=>{if(e.target===x)x.hidden=true});$('vaultForm').onsubmit=enableVault;$('clearData').onclick=clearData;document.addEventListener('visibilitychange',()=>{if(!document.hidden)poll(false)})}
async function createAccount(){let alias=$('aliasInput').value.trim();if(alias&&!/^[a-zA-Z0-9._-]{3,28}$/.test(alias)){$('aliasHint').textContent='Use 3–28 letters, numbers, dots, dashes or underscores.';$('aliasHint').classList.add('error');return}$('createBtn').disabled=true;$('createBtn').textContent='Opening relay…';try{let d=await relay('get_email_address');if(alias)d=await relay('set_email_user',{email_user:alias},d.sid_token);const address=d.email_addr||d.email;const a={address,token:d.sid_token,id:address.split('@')[0],created:Date.now(),expires:Date.now()+3600e3,seq:0};S.accounts.unshift(a);S.active=a;S.messages=[];S.history.unshift({address,created:a.created,burned:false});$('aliasInput').value='';$('createPanel').hidden=true;await save();render();startPolling();await poll(true);toast('Inbox is live for about one hour.')}catch(e){toast(friendly(e))}finally{$('createBtn').disabled=false;$('createBtn').textContent='Create address'}}
function render(){const active=!!S.active;$('emptyState').hidden=active;$('inboxView').hidden=!active;$('accountList').innerHTML=S.accounts.map(a=>`<div class="account-card ${S.active?.address===a.address?'active':''}" data-a="${esc(a.address)}"><div class="alias">${esc(a.address)}</div><div class="meta"><span>${age(a.created)}</span><span class="badge">${a.unread||0} new</span></div></div>`).join('');document.querySelectorAll('.account-card').forEach(x=>x.onclick=()=>selectAccount(S.accounts.find(a=>a.address===x.dataset.a)));$('historyCount').textContent=S.history.length;$('historyPanel').innerHTML=S.history.map(h=>`<div class="history-item">${esc(h.address)} · ${h.burned?'removed':age(h.created)}</div>`).join('')||'No past addresses.';$('vaultBtn').textContent=S.vault?'Encrypted':'Session only';if(active){$('addressText').textContent=S.active.address;updateExpiry();renderMessages()}}
async function selectAccount(a){if(!a)return;S.active=a;S.messages=[];await save();render();startPolling();poll(true)}
async function poll(manual){if(!S.active)return;try{const d=await relay('check_email',{seq:S.active.seq||0},S.active.token);S.active.token=d.sid_token||S.active.token;const list=d.list||[];S.messages=list.filter(m=>m.mail_id!==1);S.active.unread=S.messages.filter(x=>!x.mail_read).length;S.active.seq=Math.max(S.active.seq||0,...S.messages.map(x=>+x.mail_id||0));renderMessages();renderAccountsOnly();$('lastChecked').textContent='Checked just now';setApi(true);await save();if(manual)toast(S.messages.length?'Inbox refreshed':'Listening for mail')}catch(e){setApi(false);if(manual)toast(friendly(e))}}
function renderAccountsOnly(){const keep=S.active?.address;render();S.active=S.accounts.find(x=>x.address===keep)||S.active}
function renderMessages(){if(!S.active)return;$('unreadCount').textContent=S.messages.filter(x=>!x.mail_read).length;$('messageList').innerHTML=S.messages.length?S.messages.map(m=>`<div class="message-item ${m.mail_read?'':'unread'}" data-id="${m.mail_id}"><span class="time">${esc(m.mail_date||'now')}</span><div class="from">${esc(m.mail_from||'Unknown sender')}</div><div class="subject">${esc(m.mail_subject||'(No subject)')}</div><div class="intro">${esc(m.mail_excerpt||'Open to read')}</div></div>`).join(''):`<div class="empty-list"><b>Listening for messages</b>New mail will appear automatically.</div>`;document.querySelectorAll('.message-item').forEach(x=>x.onclick=()=>openMessage(x.dataset.id))}
async function openMessage(id){document.querySelectorAll('.message-item').forEach(x=>x.classList.toggle('active',x.dataset.id===id));$('reader').innerHTML='<div class="reader-empty"><p>Opening message…</p></div>';try{const m=await relay('fetch_email',{email_id:id},S.active.token);const raw=m.mail_body||m.mail_excerpt||'This message has no readable body.';const isHtml=/<[a-z][\s\S]*>/i.test(raw);const body=isHtml?'<iframe class="html-frame" sandbox="allow-popups" title="Message content"></iframe>':`<div class="message-body">${esc(raw)}</div>`;$('reader').innerHTML=`<button class="close-reader tool-btn">← Inbox</button><p class="eyebrow">Message</p><h2>${esc(m.mail_subject||'(No subject)')}</h2><div class="message-meta">From ${esc(m.mail_from||'Unknown sender')} · ${esc(m.mail_date||'')}</div>${body}`;$('reader').querySelector('.close-reader').onclick=()=>{$('reader').innerHTML='<div class="reader-empty"><span>↙</span><h3>Select a message</h3><p>The message body will open here.</p></div>'};if(isHtml){const f=$('reader').querySelector('iframe');f.srcdoc=raw.replace(/<script[\s\S]*?<\/script>/gi,'').replace(/<(img|iframe)[^>]*>/gi,'')}poll(false)}catch(e){$('reader').innerHTML=`<div class="reader-empty"><h3>Message could not open</h3><p>${esc(friendly(e))}</p></div>`}}
function startPolling(){clearInterval(S.timer);const sec=+$('intervalSelect').value;if(sec)S.timer=setInterval(()=>poll(false),sec*1000)}
function updateExpiry(){if(!S.active)return;const left=Math.max(0,S.active.expires-Date.now()),m=Math.ceil(left/60000);$('expiryText').textContent=left?`Relay keeps mail for about one hour · ${m}m local timer`:'Relay window may have expired';if(left)setTimeout(updateExpiry,30000)}
async function burn(){if(!S.active)return;const a=S.active;if(!confirm(`Remove ${a.address} from this device? Mail at the relay expires on its own.`))return;S.accounts=S.accounts.filter(x=>x!==a);const h=S.history.find(x=>x.address===a.address);if(h)h.burned=true;S.active=S.accounts[0]||null;S.messages=[];await save();render();if(S.active){startPolling();poll(true)}toast('Address removed from this device.')}
function showQR(){$('qrCode').innerHTML='';$('qrAddress').textContent=S.active.address;new QRCode($('qrCode'),{text:`mailto:${S.active.address}`,width:190,height:190,colorDark:'#261d17',colorLight:'#fffaf0',correctLevel:QRCode.CorrectLevel.M});openModal('qrModal')}
function openModal(id){$(id).hidden=false}
async function enableVault(e){e.preventDefault();const pass=$('vaultPass').value;if(pass.length<8)return toast('Use at least 8 characters.');S.key=await derive(pass);S.vault=true;await save();$('vaultModal').hidden=true;$('vaultPass').value='';render();toast('Local history encrypted for this session.')}
async function derive(pass,salt){salt=salt||crypto.getRandomValues(new Uint8Array(16));const base=await crypto.subtle.importKey('raw',new TextEncoder().encode(pass),'PBKDF2',false,['deriveKey']);const key=await crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:180000,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);return {key,salt}}
async function save(){const payload=JSON.stringify({accounts:S.accounts,history:S.history,active:S.active?.address});sessionStorage.setItem('ghostpost',payload);if(S.vault&&S.key){const iv=crypto.getRandomValues(new Uint8Array(12));const data=await crypto.subtle.encrypt({name:'AES-GCM',iv},S.key.key,new TextEncoder().encode(payload));localStorage.setItem('ghostpost-vault',JSON.stringify({salt:b64(S.key.salt),iv:b64(iv),data:b64(new Uint8Array(data))}))}}
function loadSession(){try{const d=JSON.parse(sessionStorage.getItem('ghostpost'));if(d){S.accounts=d.accounts||[];S.history=d.history||[];S.active=S.accounts.find(x=>x.address===d.active)||S.accounts[0]||null}}catch{}}
function clearData(){if(!confirm('Clear every local address and saved credential?'))return;localStorage.removeItem('ghostpost-vault');sessionStorage.removeItem('ghostpost');S.accounts=[];S.history=[];S.active=null;S.vault=false;$('vaultModal').hidden=true;render();toast('Local data cleared.')}
function copy(x){navigator.clipboard.writeText(x).then(()=>toast('Address copied.')).catch(()=>toast('Select the address and copy it manually.'))}
function age(t){const m=Math.floor((Date.now()-t)/60000);return m<1?'just now':m<60?`${m}m ago`:`${Math.floor(m/60)}h ago`}
function b64(u){return btoa(String.fromCharCode(...u))}
init();
