const API='https://api.mail.tm';
const S={accounts:[],active:null,messages:[],domain:'',timer:null,lastPoll:0,history:[],vault:false,key:null};
const $=id=>document.getElementById(id); const esc=s=>(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(m){$('toast').textContent=m;$('toast').classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>$('toast').classList.remove('show'),2400)}
function friendly(e){const s=String(e?.message||e);if(/429/.test(s))return 'The relay is busy. Wait a minute, then try again.';if(/address.*used|422/.test(s))return 'That alias is taken. Try a more unusual one.';if(/Failed to fetch|network/i.test(s))return 'The mail relay is not reachable right now.';if(/401/.test(s))return 'This inbox session expired. Make a fresh address.';return 'Something interrupted the relay. Try again in a moment.'}
async function api(path,opt={}){const r=await fetch(API+path,{...opt,headers:{'Content-Type':'application/json',...(opt.token?{Authorization:`Bearer ${opt.token}`}:{})}});if(!r.ok)throw new Error(`${r.status} ${await r.text()}`);if(r.status===204)return null;return r.json()}
async function init(){loadSession();bind();try{const d=await api('/domains?page=1');S.domain=d['hydra:member'].find(x=>x.isActive&&!x.isPrivate)?.domain||'';$('domainPreview').textContent='@'+S.domain;setApi(true)}catch(e){setApi(false)}render();if(S.active)selectAccount(S.active);}
function setApi(ok){$('apiState').textContent=ok?'Relay online':'Relay unavailable';$('apiDot').parentElement.classList.toggle('ok',ok)}
function bind(){['newBtn','heroCreate'].forEach(id=>$(id).onclick=()=>{$('createPanel').hidden=false;$('aliasInput').focus()});$('cancelCreate').onclick=()=>{$('createPanel').hidden=true};$('createBtn').onclick=createAccount;$('aliasInput').onkeydown=e=>{if(e.key==='Enter')createAccount()};$('copyBtn').onclick=()=>copy(S.active?.address);$('refreshBtn').onclick=()=>poll(true);$('deleteBtn').onclick=burn;$('intervalSelect').onchange=startPolling;$('historyBtn').onclick=()=>{$('historyPanel').hidden=!$('historyPanel').hidden};$('qrBtn').onclick=showQR;$('privacyBtn').onclick=()=>openModal('privacyModal');$('vaultBtn').onclick=()=>openModal('vaultModal');document.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>x.closest('.modal-wrap').hidden=true);document.querySelectorAll('.modal-wrap').forEach(x=>x.onclick=e=>{if(e.target===x)x.hidden=true});$('vaultForm').onsubmit=enableVault;$('clearData').onclick=clearData;document.addEventListener('visibilitychange',()=>{if(!document.hidden)poll(false)})}
function slug(){return 'ghost-'+crypto.randomUUID().slice(0,8)}
async function createAccount(){if(!S.domain)return toast('The relay is not ready yet.');let alias=$('aliasInput').value.trim()||slug();if(!/^[a-zA-Z0-9._-]{3,28}$/.test(alias)){$('aliasHint').textContent='Use 3–28 letters, numbers, dots, dashes or underscores.';$('aliasHint').classList.add('error');return}const address=`${alias}@${S.domain}`,password=crypto.randomUUID()+crypto.randomUUID();$('createBtn').disabled=true;$('createBtn').textContent='Opening relay…';try{await api('/accounts',{method:'POST',body:JSON.stringify({address,password})});const t=await api('/token',{method:'POST',body:JSON.stringify({address,password})});const a={address,password,token:t.token,id:t.id,created:Date.now(),expires:Date.now()+6*3600e3};S.accounts.unshift(a);S.active=a;S.history.unshift({address,created:a.created,burned:false});$('aliasInput').value='';$('createPanel').hidden=true;await save();render();startPolling();poll(true);toast('Inbox is live.')}catch(e){toast(friendly(e))}finally{$('createBtn').disabled=false;$('createBtn').textContent='Create address'}}
function render(){const active=!!S.active;$('emptyState').hidden=active;$('inboxView').hidden=!active;$('accountList').innerHTML=S.accounts.map(a=>`<div class="account-card ${S.active?.address===a.address?'active':''}" data-a="${esc(a.address)}"><div class="alias">${esc(a.address)}</div><div class="meta"><span>${age(a.created)}</span><span class="badge">${a.unread||0} new</span></div></div>`).join('');document.querySelectorAll('.account-card').forEach(x=>x.onclick=()=>selectAccount(S.accounts.find(a=>a.address===x.dataset.a)));$('historyCount').textContent=S.history.length;$('historyPanel').innerHTML=S.history.map(h=>`<div class="history-item">${esc(h.address)} · ${h.burned?'burned':age(h.created)}</div>`).join('')||'No past addresses.';$('vaultBtn').textContent=S.vault?'Encrypted':'Session only';if(active){$('addressText').textContent=S.active.address;updateExpiry();renderMessages()}}
async function selectAccount(a){if(!a)return;S.active=a;await save();render();startPolling();poll(true)}
async function poll(manual){if(!S.active)return;try{const d=await api('/messages?page=1',{token:S.active.token});S.messages=d['hydra:member']||[];S.active.unread=S.messages.filter(x=>!x.seen).length;S.lastPoll=Date.now();renderMessages();renderAccountsOnly();$('lastChecked').textContent='Checked just now';setApi(true);if(manual)toast(S.messages.length?'Inbox refreshed':'Listening for mail')}catch(e){setApi(false);if(manual)toast(friendly(e))}}
function renderAccountsOnly(){const keep=S.active?.address;render();S.active=S.accounts.find(x=>x.address===keep)||S.active}
function renderMessages(){if(!S.active)return;$('unreadCount').textContent=S.messages.filter(x=>!x.seen).length;$('messageList').innerHTML=S.messages.length?S.messages.map(m=>`<div class="message-item ${m.seen?'':'unread'}" data-id="${m.id}"><span class="time">${clock(m.createdAt)}</span><div class="from">${esc(m.from?.name||m.from?.address||'Unknown sender')}</div><div class="subject">${esc(m.subject||'(No subject)')}</div><div class="intro">${esc(m.intro||'Open to read')}</div></div>`).join(''):`<div class="empty-list"><b>Listening for messages</b>New mail will appear automatically.</div>`;document.querySelectorAll('.message-item').forEach(x=>x.onclick=()=>openMessage(x.dataset.id));}
async function openMessage(id){document.querySelectorAll('.message-item').forEach(x=>x.classList.toggle('active',x.dataset.id===id));$('reader').innerHTML='<div class="reader-empty"><p>Opening message…</p></div>';try{const m=await api('/messages/'+id,{token:S.active.token});const from=m.from?.name?`${m.from.name} <${m.from.address}>`:m.from?.address||'Unknown sender';let body=m.html?.length?`<iframe class="html-frame" sandbox="allow-popups" title="Message content"></iframe>`:`<div class="message-body">${esc(m.text||m.intro||'This message has no readable body.')}</div>`;let at=(m.attachments||[]).map(a=>`<a class="attachment" href="${API}${a.downloadUrl}" target="_blank" rel="noreferrer">↓ ${esc(a.filename)} · ${bytes(a.size)}</a>`).join('');$('reader').innerHTML=`<button class="close-reader tool-btn">← Inbox</button><p class="eyebrow">Message</p><h2>${esc(m.subject||'(No subject)')}</h2><div class="message-meta">From ${esc(from)} · ${new Date(m.createdAt).toLocaleString()}</div>${body}${at?`<div class="attachments">${at}</div>`:''}`;$('reader').querySelector('.close-reader').onclick=()=>{$('reader').innerHTML='<div class="reader-empty"><span>↙</span><h3>Select a message</h3><p>The message body and attachments will open here.</p></div>'};if(m.html?.length){const f=$('reader').querySelector('iframe');f.srcdoc=(Array.isArray(m.html)?m.html.join(''):m.html).replace(/<script[\s\S]*?<\/script>/gi,'')}poll(false)}catch(e){$('reader').innerHTML=`<div class="reader-empty"><h3>Message could not open</h3><p>${esc(friendly(e))}</p></div>`}}
function startPolling(){clearInterval(S.timer);const sec=+$('intervalSelect').value;if(sec)S.timer=setInterval(()=>poll(false),sec*1000)}
function updateExpiry(){if(!S.active)return;const left=Math.max(0,S.active.expires-Date.now()),h=Math.floor(left/3600e3),m=Math.floor((left%3600e3)/60000);$('expiryText').textContent=`Local session window · ${h}h ${m}m remaining`;if(left)requestAnimationFrame(()=>setTimeout(updateExpiry,30000))}
async function burn(){if(!S.active)return;const a=S.active;if(!confirm(`Burn ${a.address}? It will disappear from this device.`))return;try{await api('/accounts/'+a.id,{method:'DELETE',token:a.token})}catch{}S.accounts=S.accounts.filter(x=>x!==a);const h=S.history.find(x=>x.address===a.address);if(h)h.burned=true;S.active=S.accounts[0]||null;S.messages=[];await save();render();if(S.active){startPolling();poll(true)}toast('Address burned locally.')}
function showQR(){$('qrCode').innerHTML='';$('qrAddress').textContent=S.active.address;new QRCode($('qrCode'),{text:`mailto:${S.active.address}`,width:190,height:190,colorDark:'#080b12',colorLight:'#ffffff',correctLevel:QRCode.CorrectLevel.M});openModal('qrModal')}
function openModal(id){$(id).hidden=false}
async function enableVault(e){e.preventDefault();const pass=$('vaultPass').value;if(pass.length<8)return toast('Use at least 8 characters.');S.key=await derive(pass);S.vault=true;await save();$('vaultModal').hidden=true;$('vaultPass').value='';render();toast('Local history encrypted.')}
async function derive(pass,salt){salt=salt||crypto.getRandomValues(new Uint8Array(16));const base=await crypto.subtle.importKey('raw',new TextEncoder().encode(pass),'PBKDF2',false,['deriveKey']);const key=await crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:180000,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);return {key,salt}}
async function save(){const payload=JSON.stringify({accounts:S.accounts,history:S.history,active:S.active?.address});sessionStorage.setItem('ghostpost',payload);if(S.vault&&S.key){const iv=crypto.getRandomValues(new Uint8Array(12));const data=await crypto.subtle.encrypt({name:'AES-GCM',iv},S.key.key,new TextEncoder().encode(payload));localStorage.setItem('ghostpost-vault',JSON.stringify({salt:b64(S.key.salt),iv:b64(iv),data:b64(new Uint8Array(data))}))}}
function loadSession(){try{const d=JSON.parse(sessionStorage.getItem('ghostpost'));if(d){S.accounts=d.accounts||[];S.history=d.history||[];S.active=S.accounts.find(x=>x.address===d.active)||S.accounts[0]||null}}catch{}}
function clearData(){if(!confirm('Clear every local address and saved credential?'))return;localStorage.removeItem('ghostpost-vault');sessionStorage.removeItem('ghostpost');S.accounts=[];S.history=[];S.active=null;S.vault=false;$('vaultModal').hidden=true;render();toast('Local data cleared.')}
function copy(x){navigator.clipboard.writeText(x).then(()=>toast('Address copied.'))}
function age(t){const m=Math.floor((Date.now()-t)/60000);return m<1?'just now':m<60?`${m}m ago`:`${Math.floor(m/60)}h ago`}
function clock(t){return new Date(t).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}
function bytes(n){return n>1048576?(n/1048576).toFixed(1)+' MB':Math.ceil(n/1024)+' KB'}
function b64(u){return btoa(String.fromCharCode(...u))}
init();
